# Generated by Django 3.2.25 on 2024-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0009_embedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='action_text',
            field=models.CharField(default='Перейти', max_length=50, verbose_name='Текст на кнопке'),
        ),
    ]
